apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx:1.28.0
    ports:
    - containerPort: 8000 
    volumeMounts:
      - name: shared-volume
        mountPath: /homework
      - name: nginx-config-volume
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf # Mount only the nginx.conf file
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -Rf /homework/index.html"]
        
  initContainers:
    - name: downloader
      image: busybox:1.28
      command:
      - wget
      - "-O"
      - "/init/index.html"
      - https://otus.ru
      volumeMounts:
      - name: shared-volume
        mountPath: "/init"
  dnsPolicy: Default
  volumes:
    - name: shared-volume
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-custom-config

---
# в задании у сервера 8000 порт, отсюда и конфиг мап

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        server {
            listen 8000; # Change this to your desired port
            server_name localhost;

            location / {
                root /homework;
                index index.html index.htm;
            }
        }
    }